---
- name: Download Node.js LTS Installation Script
  become: no
  get_url:
      url: "https://deb.nodesource.com/setup_{{node_lts_version}}.x"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/setup_lts.x.sh"
      mode: 0554
  when: (ansible_distribution == "Ubuntu") and (node_install_lts)

- name: Download Node.js LTS Installation Script
  become: no
  get_url:
      url: "https://rpm.nodesource.com/setup_{{node_lts_version}}.x"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/setup_lts.x.sh"
      mode: 0554
  when: (ansible_distribution == "RedHat") and (node_install_lts)

- name: Install Node.js LTS
  become: yes
  shell: "{{ansible_user_dir}}/{{base_download_directory}}/setup_lts.x.sh"
  args:
      creates: /usr/bin/node
  when: node_install_lts

- name: Download Node.js Current Installation Script
  become: no
  get_url:
      url: "https://deb.nodesource.com/setup_{{node_current_version}}.x"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/setup_current.x.sh"
      mode: 0554
  when: (ansible_distribution == "Ubuntu") and (node_install_current)

- name: Download Node.js Current Installation Script
  become: no
  get_url:
      url: "https://rpm.nodesource.com/setup_{{node_current_version}}.x"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/setup_current.x.sh"
      mode: 0554
  when: (ansible_distribution == "RedHat") and (node_install_current)

- name: Install Node.js Current
  become: yes
  shell: "{{ansible_user_dir}}/{{base_download_directory}}/setup_current.x.sh"
  args:
      creates: /usr/bin/node
  when: node_install_current

- name: Install Node.js And Tools
  become: yes
  apt:
      name: "{{ item }}"
      state: present
  loop:
      - nodejs
      - build-essential
  when: (ansible_distribution == "Ubuntu") and (node_install)

- name: Install Node.js And Tools
  become: yes
  yum:
      name: "{{ item }}"
      state: present
  loop:
      - nodejs
      - "@Development Tools"
  when: (ansible_distribution == "RedHat") and (node_install)

- name: Test Installation
  become: no
  shell: "{{ item }}"
  loop:
      - "node --version"
      - "npm --version"
